name: visualizer
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - numpy=1.25
  - matplotlib
  - scikit-image
  - sharedarray
  - scipy=1.11
  - pkgconfig=1.5
  - silx=1.1
  - h5py=3.9.0
  - pyepics
  - python-dotenv
  - pip:
    - git+https://gitlab.cnpem.br/GCC/ssc-pimega
